// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class GestureInputSystemGameReadyHandler {
        
        private uFrame.Kernel.GameReadyEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private object ActionNode70_key = default( System.Object );
        
        private int IntNode105 = 0;
        
        private bool ActionNode70_thumb = default( System.Boolean );
        
        private bool BoolNode71 = true;
        
        private bool ActionNode70_index = default( System.Boolean );
        
        private bool ActionNode70_middle = default( System.Boolean );
        
        private bool BoolNode72 = false;
        
        private bool ActionNode70_fourth = default( System.Boolean );
        
        private bool ActionNode70_fifth = default( System.Boolean );
        
        private object ActionNode111_key = default( System.Object );
        
        private int IntNode106 = 1;
        
        private bool ActionNode111_thumb = default( System.Boolean );
        
        private bool ActionNode111_index = default( System.Boolean );
        
        private bool ActionNode111_middle = default( System.Boolean );
        
        private bool ActionNode111_fourth = default( System.Boolean );
        
        private bool ActionNode111_fifth = default( System.Boolean );
        
        private object ActionNode112_key = default( System.Object );
        
        private int IntNode107 = 2;
        
        private bool ActionNode112_thumb = default( System.Boolean );
        
        private bool ActionNode112_index = default( System.Boolean );
        
        private bool ActionNode112_middle = default( System.Boolean );
        
        private bool ActionNode112_fourth = default( System.Boolean );
        
        private bool ActionNode112_fifth = default( System.Boolean );
        
        private object ActionNode113_key = default( System.Object );
        
        private int IntNode108 = 3;
        
        private bool ActionNode113_thumb = default( System.Boolean );
        
        private bool ActionNode113_index = default( System.Boolean );
        
        private bool ActionNode113_middle = default( System.Boolean );
        
        private bool ActionNode113_fourth = default( System.Boolean );
        
        private bool ActionNode113_fifth = default( System.Boolean );
        
        private object ActionNode114_key = default( System.Object );
        
        private int IntNode109 = 4;
        
        private bool ActionNode114_thumb = default( System.Boolean );
        
        private bool ActionNode114_index = default( System.Boolean );
        
        private bool ActionNode114_middle = default( System.Boolean );
        
        private bool ActionNode114_fourth = default( System.Boolean );
        
        private bool ActionNode114_fifth = default( System.Boolean );
        
        private object ActionNode132_key = default( System.Object );
        
        private int IntNode133 = 5;
        
        private bool ActionNode132_thumb = default( System.Boolean );
        
        private bool ActionNode132_index = default( System.Boolean );
        
        private bool ActionNode132_middle = default( System.Boolean );
        
        private bool ActionNode132_fourth = default( System.Boolean );
        
        private bool ActionNode132_fifth = default( System.Boolean );
        
        private object ActionNode135_key = default( System.Object );
        
        private int IntNode136 = 6;
        
        private bool ActionNode135_thumb = default( System.Boolean );
        
        private bool ActionNode135_index = default( System.Boolean );
        
        private bool ActionNode135_middle = default( System.Boolean );
        
        private bool ActionNode135_fourth = default( System.Boolean );
        
        private bool ActionNode135_fifth = default( System.Boolean );
        
        private TetrisDB.GestureUpdateEvent PublishEventNode81_Result = default( TetrisDB.GestureUpdateEvent );
        
        public uFrame.Kernel.GameReadyEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode70_key = IntNode105;
            ActionNode70_thumb = BoolNode71;
            ActionNode70_index = BoolNode71;
            ActionNode70_middle = BoolNode72;
            ActionNode70_fourth = BoolNode72;
            ActionNode70_fifth = BoolNode72;
            // ActionNode
            while (this.DebugInfo("a876787c-d3b6-43dc-9673-ca5866291deb","67b36efb-ac9d-427e-9d9c-512ac104e0cd", this) == 1) yield return null;
            // Visit GestureUtils.registerGesture
            GestureUtils.registerGesture(ActionNode70_key, ActionNode70_thumb, ActionNode70_index, ActionNode70_middle, ActionNode70_fourth, ActionNode70_fifth);
            ActionNode111_key = IntNode106;
            ActionNode111_thumb = BoolNode71;
            ActionNode111_index = BoolNode71;
            ActionNode111_middle = BoolNode71;
            ActionNode111_fourth = BoolNode72;
            ActionNode111_fifth = BoolNode72;
            // ActionNode
            while (this.DebugInfo("67b36efb-ac9d-427e-9d9c-512ac104e0cd","7cf242e3-b774-4d20-945d-1759f3efa0c1", this) == 1) yield return null;
            // Visit GestureUtils.registerGesture
            GestureUtils.registerGesture(ActionNode111_key, ActionNode111_thumb, ActionNode111_index, ActionNode111_middle, ActionNode111_fourth, ActionNode111_fifth);
            ActionNode112_key = IntNode107;
            ActionNode112_thumb = BoolNode71;
            ActionNode112_index = BoolNode71;
            ActionNode112_middle = BoolNode71;
            ActionNode112_fourth = BoolNode71;
            ActionNode112_fifth = BoolNode72;
            // ActionNode
            while (this.DebugInfo("7cf242e3-b774-4d20-945d-1759f3efa0c1","192e3404-a699-4f7b-8640-e2dfac68b774", this) == 1) yield return null;
            // Visit GestureUtils.registerGesture
            GestureUtils.registerGesture(ActionNode112_key, ActionNode112_thumb, ActionNode112_index, ActionNode112_middle, ActionNode112_fourth, ActionNode112_fifth);
            ActionNode113_key = IntNode108;
            ActionNode113_thumb = BoolNode72;
            ActionNode113_index = BoolNode71;
            ActionNode113_middle = BoolNode71;
            ActionNode113_fourth = BoolNode71;
            ActionNode113_fifth = BoolNode71;
            // ActionNode
            while (this.DebugInfo("192e3404-a699-4f7b-8640-e2dfac68b774","9cea2b15-4c88-40eb-bdd1-1809bf5c3dbb", this) == 1) yield return null;
            // Visit GestureUtils.registerGesture
            GestureUtils.registerGesture(ActionNode113_key, ActionNode113_thumb, ActionNode113_index, ActionNode113_middle, ActionNode113_fourth, ActionNode113_fifth);
            ActionNode114_key = IntNode109;
            ActionNode114_thumb = BoolNode71;
            ActionNode114_index = BoolNode71;
            ActionNode114_middle = BoolNode71;
            ActionNode114_fourth = BoolNode71;
            ActionNode114_fifth = BoolNode71;
            // ActionNode
            while (this.DebugInfo("9cea2b15-4c88-40eb-bdd1-1809bf5c3dbb","1e79d8a3-b784-4dfb-baa0-cd189321711f", this) == 1) yield return null;
            // Visit GestureUtils.registerGesture
            GestureUtils.registerGesture(ActionNode114_key, ActionNode114_thumb, ActionNode114_index, ActionNode114_middle, ActionNode114_fourth, ActionNode114_fifth);
            ActionNode132_key = IntNode133;
            ActionNode132_thumb = BoolNode71;
            ActionNode132_index = BoolNode72;
            ActionNode132_middle = BoolNode72;
            ActionNode132_fourth = BoolNode72;
            ActionNode132_fifth = BoolNode72;
            // ActionNode
            while (this.DebugInfo("1e79d8a3-b784-4dfb-baa0-cd189321711f","cc652384-a7b9-4580-9456-bca1c4243fc7", this) == 1) yield return null;
            // Visit GestureUtils.registerGesture
            GestureUtils.registerGesture(ActionNode132_key, ActionNode132_thumb, ActionNode132_index, ActionNode132_middle, ActionNode132_fourth, ActionNode132_fifth);
            ActionNode135_key = IntNode136;
            ActionNode135_thumb = BoolNode72;
            ActionNode135_index = BoolNode71;
            ActionNode135_middle = BoolNode71;
            ActionNode135_fourth = BoolNode72;
            ActionNode135_fifth = BoolNode71;
            // ActionNode
            while (this.DebugInfo("cc652384-a7b9-4580-9456-bca1c4243fc7","307f959d-2914-4aa7-b056-e224e1654c12", this) == 1) yield return null;
            // Visit GestureUtils.registerGesture
            GestureUtils.registerGesture(ActionNode135_key, ActionNode135_thumb, ActionNode135_index, ActionNode135_middle, ActionNode135_fourth, ActionNode135_fifth);
            // PublishEventNode
            while (this.DebugInfo("307f959d-2914-4aa7-b056-e224e1654c12","8cb82bb7-2d9d-452b-ba92-12398c02e1b6", this) == 1) yield return null;
            var PublishEventNode81_Event = new GestureUpdateEvent();
            System.Publish(PublishEventNode81_Event);
            PublishEventNode81_Result = PublishEventNode81_Event;
            yield break;
        }
    }
}
