// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using Leap;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class GestureInputSystemGestureUpdateEventHandler {
        
        private TetrisDB.GestureUpdateEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private int ActionNode127_Milliseconds = default( System.Int32 );
        
        private int IntNode83 = 500;
        
        private uFrame.Actions.MillitTimer ActionNode127 = new uFrame.Actions.MillitTimer();
        
        private TetrisDB.GestureUpdateEvent PublishEventNode84_Result = default( TetrisDB.GestureUpdateEvent );
        
        private Leap.Frame ActionNode74_Result = default( Leap.Frame );
        
        private Leap.Frame ActionNode75_frame = default( Leap.Frame );
        
        private Leap.Hand ActionNode75_left = default( Leap.Hand );
        
        private object ActionNode76_toCheck = default( System.Object );
        
        private TetrisDB.HandInvisibleEvent PublishEventNode182_Result = default( TetrisDB.HandInvisibleEvent );
        
        private TetrisDB.HandVisibleEvent PublishEventNode183_Result = default( TetrisDB.HandVisibleEvent );
        
        private object ActionNode77_key = default( System.Object );
        
        private int IntNode85 = 0;
        
        private Leap.Hand ActionNode77_hand = default( Leap.Hand );
        
        private TetrisDB.ActiveGroupMoveLeftEvent PublishEventNode79_Result = default( TetrisDB.ActiveGroupMoveLeftEvent );
        
        private object ActionNode119_key = default( System.Object );
        
        private int IntNode102 = 1;
        
        private Leap.Hand ActionNode119_hand = default( Leap.Hand );
        
        private TetrisDB.ActiveGroupMoveRightEvent PublishEventNode115_Result = default( TetrisDB.ActiveGroupMoveRightEvent );
        
        private object ActionNode95_key = default( System.Object );
        
        private int IntNode96 = 2;
        
        private Leap.Hand ActionNode95_hand = default( Leap.Hand );
        
        private TetrisDB.ActiveGroupRotateEvent PublishEventNode116_Result = default( TetrisDB.ActiveGroupRotateEvent );
        
        private object ActionNode120_key = default( System.Object );
        
        private int IntNode103 = 3;
        
        private Leap.Hand ActionNode120_hand = default( Leap.Hand );
        
        private TetrisDB.ActiveGroupDownEvent PublishEventNode117_Result = default( TetrisDB.ActiveGroupDownEvent );
        
        private object ActionNode128_key = default( System.Object );
        
        private int IntNode129 = 4;
        
        private Leap.Hand ActionNode128_hand = default( Leap.Hand );
        
        private TetrisDB.MenuOpenEvent PublishEventNode148_Result = default( TetrisDB.MenuOpenEvent );
        
        private object ActionNode137_key = default( System.Object );
        
        private int IntNode138 = 5;
        
        private Leap.Hand ActionNode137_hand = default( Leap.Hand );
        
        private TetrisDB.MenuCloseEvent PublishEventNode149_Result = default( TetrisDB.MenuCloseEvent );
        
        private object ActionNode141_key = default( System.Object );
        
        private int IntNode142 = 6;
        
        private Leap.Hand ActionNode141_hand = default( Leap.Hand );
        
        private TetrisDB.GameExitEvent PublishEventNode150_Result = default( TetrisDB.GameExitEvent );
        
        public TetrisDB.GestureUpdateEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode127_Milliseconds = IntNode83;
            // ActionNode
            while (this.DebugInfo("bf1a89a3-98e0-4803-b7a0-808be2646fd3","d9eb14db-b5db-40c3-bd01-a36f90258104", this) == 1) yield return null;
            // Visit uFrame.Actions.MillitTimer
            ActionNode127.Milliseconds = ActionNode127_Milliseconds;
            ActionNode127.System = System;
            ActionNode127.Complete = ()=> { System.StartCoroutine(ActionNode127_Complete()); };
            ActionNode127.Execute();
            // ActionNode
            while (this.DebugInfo("9fe12bc1-ff95-4ca9-87af-04bf3d20f34d","730a328a-620a-408f-b020-1ec2c12ed328", this) == 1) yield return null;
            // Visit FrameUtils.getFrame
            ActionNode74_Result = FrameUtils.getFrame();
            ActionNode75_frame = ActionNode74_Result;
            // ActionNode
            while (this.DebugInfo("730a328a-620a-408f-b020-1ec2c12ed328","b83a3922-04bf-45ae-86ef-4cf556cad129", this) == 1) yield return null;
            // Visit FrameUtils.getLeftHandFromFrame
            FrameUtils.getLeftHandFromFrame(ActionNode75_frame, out ActionNode75_left);
            ActionNode76_toCheck = ActionNode75_left;
            // ActionNode
            while (this.DebugInfo("b83a3922-04bf-45ae-86ef-4cf556cad129","222aae32-7144-4f27-8cfc-34f6ccaad846", this) == 1) yield return null;
            // Visit ConditionsUtils.isNull
            ConditionsUtils.isNull(ActionNode76_toCheck, ()=> { System.StartCoroutine(ActionNode76_yes()); }, ()=> { System.StartCoroutine(ActionNode76_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode127_Complete() {
            // PublishEventNode
            while (this.DebugInfo("d9eb14db-b5db-40c3-bd01-a36f90258104","9fe12bc1-ff95-4ca9-87af-04bf3d20f34d", this) == 1) yield return null;
            var PublishEventNode84_Event = new GestureUpdateEvent();
            System.Publish(PublishEventNode84_Event);
            PublishEventNode84_Result = PublishEventNode84_Event;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode76_yes() {
            // PublishEventNode
            while (this.DebugInfo("222aae32-7144-4f27-8cfc-34f6ccaad846","d2ac992c-2c35-421f-af1e-a9c12500ef9e", this) == 1) yield return null;
            var PublishEventNode182_Event = new HandInvisibleEvent();
            System.Publish(PublishEventNode182_Event);
            PublishEventNode182_Result = PublishEventNode182_Event;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode77_yes() {
            // PublishEventNode
            while (this.DebugInfo("2e85193b-7f96-4150-a0cd-ed5a3e0a5015","b650c064-1158-4d64-b429-56d62b2c1f71", this) == 1) yield return null;
            var PublishEventNode79_Event = new ActiveGroupMoveLeftEvent();
            System.Publish(PublishEventNode79_Event);
            PublishEventNode79_Result = PublishEventNode79_Event;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode119_yes() {
            // PublishEventNode
            while (this.DebugInfo("2e1347d4-50a6-40e2-9e29-0a555be53310","6c87a3da-3586-409b-ab68-3f56ce6f1348", this) == 1) yield return null;
            var PublishEventNode115_Event = new ActiveGroupMoveRightEvent();
            System.Publish(PublishEventNode115_Event);
            PublishEventNode115_Result = PublishEventNode115_Event;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode95_yes() {
            // PublishEventNode
            while (this.DebugInfo("26fa5271-6740-4e31-8e9e-96efd3c4abe4","0f6a65f9-97c5-4c04-b607-69895038ff3a", this) == 1) yield return null;
            var PublishEventNode116_Event = new ActiveGroupRotateEvent();
            System.Publish(PublishEventNode116_Event);
            PublishEventNode116_Result = PublishEventNode116_Event;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode120_yes() {
            // PublishEventNode
            while (this.DebugInfo("21f82ff7-ca5e-455f-9bec-36e5f5254592","c4db65f6-2521-4ee9-96de-74990e6603b8", this) == 1) yield return null;
            var PublishEventNode117_Event = new ActiveGroupDownEvent();
            System.Publish(PublishEventNode117_Event);
            PublishEventNode117_Result = PublishEventNode117_Event;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode128_yes() {
            // PublishEventNode
            while (this.DebugInfo("e59a3bb6-2d85-4c93-9deb-c7263b07b692","124cdb4f-9a72-4b51-b8e6-e3b686410614", this) == 1) yield return null;
            var PublishEventNode148_Event = new MenuOpenEvent();
            System.Publish(PublishEventNode148_Event);
            PublishEventNode148_Result = PublishEventNode148_Event;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode137_yes() {
            // PublishEventNode
            while (this.DebugInfo("9c14444c-0151-4c06-b9f3-87828a85ea9c","696d1bc1-8d07-46d6-91dc-3e9f9095fbee", this) == 1) yield return null;
            var PublishEventNode149_Event = new MenuCloseEvent();
            System.Publish(PublishEventNode149_Event);
            PublishEventNode149_Result = PublishEventNode149_Event;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode141_yes() {
            // PublishEventNode
            while (this.DebugInfo("4f297f36-e4f7-4b4c-8e45-0804865a2c10","7189f257-b99a-4dea-a522-7948a385c9de", this) == 1) yield return null;
            var PublishEventNode150_Event = new GameExitEvent();
            System.Publish(PublishEventNode150_Event);
            PublishEventNode150_Result = PublishEventNode150_Event;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode141_no() {
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode137_no() {
            ActionNode141_key = IntNode142;
            ActionNode141_hand = ActionNode75_left;
            // ActionNode
            while (this.DebugInfo("696d1bc1-8d07-46d6-91dc-3e9f9095fbee","4f297f36-e4f7-4b4c-8e45-0804865a2c10", this) == 1) yield return null;
            // Visit GestureUtils.isGestureSatisified
            GestureUtils.isGestureSatisified(ActionNode141_key, ActionNode141_hand, ()=> { System.StartCoroutine(ActionNode141_yes()); }, ()=> { System.StartCoroutine(ActionNode141_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode128_no() {
            ActionNode137_key = IntNode138;
            ActionNode137_hand = ActionNode75_left;
            // ActionNode
            while (this.DebugInfo("124cdb4f-9a72-4b51-b8e6-e3b686410614","9c14444c-0151-4c06-b9f3-87828a85ea9c", this) == 1) yield return null;
            // Visit GestureUtils.isGestureSatisified
            GestureUtils.isGestureSatisified(ActionNode137_key, ActionNode137_hand, ()=> { System.StartCoroutine(ActionNode137_yes()); }, ()=> { System.StartCoroutine(ActionNode137_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode120_no() {
            ActionNode128_key = IntNode129;
            ActionNode128_hand = ActionNode75_left;
            // ActionNode
            while (this.DebugInfo("c4db65f6-2521-4ee9-96de-74990e6603b8","e59a3bb6-2d85-4c93-9deb-c7263b07b692", this) == 1) yield return null;
            // Visit GestureUtils.isGestureSatisified
            GestureUtils.isGestureSatisified(ActionNode128_key, ActionNode128_hand, ()=> { System.StartCoroutine(ActionNode128_yes()); }, ()=> { System.StartCoroutine(ActionNode128_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode95_no() {
            ActionNode120_key = IntNode103;
            ActionNode120_hand = ActionNode75_left;
            // ActionNode
            while (this.DebugInfo("0f6a65f9-97c5-4c04-b607-69895038ff3a","21f82ff7-ca5e-455f-9bec-36e5f5254592", this) == 1) yield return null;
            // Visit GestureUtils.isGestureSatisified
            GestureUtils.isGestureSatisified(ActionNode120_key, ActionNode120_hand, ()=> { System.StartCoroutine(ActionNode120_yes()); }, ()=> { System.StartCoroutine(ActionNode120_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode119_no() {
            ActionNode95_key = IntNode96;
            ActionNode95_hand = ActionNode75_left;
            // ActionNode
            while (this.DebugInfo("6c87a3da-3586-409b-ab68-3f56ce6f1348","26fa5271-6740-4e31-8e9e-96efd3c4abe4", this) == 1) yield return null;
            // Visit GestureUtils.isGestureSatisified
            GestureUtils.isGestureSatisified(ActionNode95_key, ActionNode95_hand, ()=> { System.StartCoroutine(ActionNode95_yes()); }, ()=> { System.StartCoroutine(ActionNode95_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode77_no() {
            ActionNode119_key = IntNode102;
            ActionNode119_hand = ActionNode75_left;
            // ActionNode
            while (this.DebugInfo("b650c064-1158-4d64-b429-56d62b2c1f71","2e1347d4-50a6-40e2-9e29-0a555be53310", this) == 1) yield return null;
            // Visit GestureUtils.isGestureSatisified
            GestureUtils.isGestureSatisified(ActionNode119_key, ActionNode119_hand, ()=> { System.StartCoroutine(ActionNode119_yes()); }, ()=> { System.StartCoroutine(ActionNode119_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode76_no() {
            // PublishEventNode
            while (this.DebugInfo("d2ac992c-2c35-421f-af1e-a9c12500ef9e","bf6405b3-8cb0-4225-9caf-42c5d45efbe8", this) == 1) yield return null;
            var PublishEventNode183_Event = new HandVisibleEvent();
            System.Publish(PublishEventNode183_Event);
            PublishEventNode183_Result = PublishEventNode183_Event;
            ActionNode77_key = IntNode85;
            ActionNode77_hand = ActionNode75_left;
            // ActionNode
            while (this.DebugInfo("bf6405b3-8cb0-4225-9caf-42c5d45efbe8","2e85193b-7f96-4150-a0cd-ed5a3e0a5015", this) == 1) yield return null;
            // Visit GestureUtils.isGestureSatisified
            GestureUtils.isGestureSatisified(ActionNode77_key, ActionNode77_hand, ()=> { System.StartCoroutine(ActionNode77_yes()); }, ()=> { System.StartCoroutine(ActionNode77_no()); });
            yield break;
        }
    }
}
