// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using Leap;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class GestureInputSystemUpdateHandler {
        
        private uFrame.ECS.ISystemUpdate _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private Leap.Frame ActionNode74_Result = default( Leap.Frame );
        
        private Leap.Frame ActionNode75_frame = default( Leap.Frame );
        
        private Leap.Hand ActionNode75_left = default( Leap.Hand );
        
        private object ActionNode76_toCheck = default( System.Object );
        
        private object ActionNode77_key = default( System.Object );
        
        private int IntNode78 = 0;
        
        private Leap.Hand ActionNode77_hand = default( Leap.Hand );
        
        public uFrame.ECS.ISystemUpdate Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // ActionNode
            while (this.DebugInfo("07bbc684-5d71-4a13-bed3-85b36cb8a326","c16c1016-dfe9-4194-9806-3d87a36f8ee0", this) == 1) yield return null;
            // Visit FrameUtils.getFrame
            ActionNode74_Result = FrameUtils.getFrame();
            ActionNode75_frame = ActionNode74_Result;
            // ActionNode
            while (this.DebugInfo("c16c1016-dfe9-4194-9806-3d87a36f8ee0","d3f71bca-007d-4c03-81bc-ea4cfb8c2e81", this) == 1) yield return null;
            // Visit FrameUtils.getLeftHandFromFrame
            FrameUtils.getLeftHandFromFrame(ActionNode75_frame, out ActionNode75_left);
            ActionNode76_toCheck = ActionNode75_left;
            // ActionNode
            while (this.DebugInfo("d3f71bca-007d-4c03-81bc-ea4cfb8c2e81","d5688bf0-b625-4f44-a8a5-02a6a81effea", this) == 1) yield return null;
            // Visit ConditionsUtils.isNull
            ConditionsUtils.isNull(ActionNode76_toCheck, ()=> { System.StartCoroutine(ActionNode76_yes()); }, ()=> { System.StartCoroutine(ActionNode76_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode76_yes() {
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode77_yes() {
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode77_no() {
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode76_no() {
            ActionNode77_key = IntNode78;
            ActionNode77_hand = ActionNode75_left;
            // ActionNode
            while (this.DebugInfo("d5688bf0-b625-4f44-a8a5-02a6a81effea","1eb198e2-e982-4f81-8f94-433730327641", this) == 1) yield return null;
            // Visit GestureUtils.isGestureSatisified
            GestureUtils.isGestureSatisified(ActionNode77_key, ActionNode77_hand, ()=> { System.StartCoroutine(ActionNode77_yes()); }, ()=> { System.StartCoroutine(ActionNode77_no()); });
            yield break;
        }
    }
}
