// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class GroupSystemGroupMoveEventPublisherHandler {
        
        private TetrisDB.GroupMoveEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private int ActionNode27_Minutes = default( System.Int32 );
        
        private int ActionNode27_Seconds = default( System.Int32 );
        
        private int IntNode28 = 1;
        
        private uFrame.Actions.Timer ActionNode27 = new uFrame.Actions.Timer();
        
        private TetrisDB.GroupMoveEvent PublishEventNode29_Result = default( TetrisDB.GroupMoveEvent );
        
        public TetrisDB.GroupMoveEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode27_Seconds = IntNode28;
            // ActionNode
            while (this.DebugInfo("3f6df7b7-6f60-49de-b29f-9a23e23226d2","707cfcd3-f5b0-43d2-8ac3-684a40e67458", this) == 1) yield return null;
            // Visit uFrame.Actions.Timer
            ActionNode27.Seconds = ActionNode27_Seconds;
            ActionNode27.System = System;
            ActionNode27.Complete = ()=> { System.StartCoroutine(ActionNode27_Complete()); };
            ActionNode27.Execute();
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode27_Complete() {
            // PublishEventNode
            while (this.DebugInfo("707cfcd3-f5b0-43d2-8ac3-684a40e67458","3dbfd24a-fcdb-47eb-bd5c-08b10531dc5d", this) == 1) yield return null;
            var PublishEventNode29_Event = new GroupMoveEvent();
            System.Publish(PublishEventNode29_Event);
            PublishEventNode29_Result = PublishEventNode29_Event;
            yield break;
        }
    }
}
