// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using TetrisDB;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class GroupSystemGroupMoveEventHandler {
        
        public GroupComponent Group;
        
        private TetrisDB.GroupMoveEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private bool ActionNode30_value = default( System.Boolean );
        
        private TetrisDB.GroupComponent ActionNode31_component = default( TetrisDB.GroupComponent );
        
        private bool BoolNode33 = false;
        
        private TetrisDB.GroupShouldSpawnEvent PublishEventNode34_Result = default( TetrisDB.GroupShouldSpawnEvent );
        
        public TetrisDB.GroupMoveEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode30_value = Group.isActive;
            // ActionNode
            while (this.DebugInfo("63a4eb4a-bf6a-420c-b283-f294fcb6f703","0ba78f37-2228-48a9-aa07-f2076c7f5fdd", this) == 1) yield return null;
            // Visit uFrame.Actions.Comparisons.IsTrue
            uFrame.Actions.Comparisons.IsTrue(ActionNode30_value, ()=> { System.StartCoroutine(ActionNode30_yes()); }, ()=> { System.StartCoroutine(ActionNode30_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode31_yes() {
            // SetVariableNode
            while (this.DebugInfo("b77ce3ed-39d6-4f12-b4eb-b27fd3f871ab","f5e9860e-5ebd-4122-bf6f-3b1c5acbe0b0", this) == 1) yield return null;
            Group.isActive = (System.Boolean)BoolNode33;
            // PublishEventNode
            while (this.DebugInfo("f5e9860e-5ebd-4122-bf6f-3b1c5acbe0b0","e3f5e492-b904-4a14-8c5a-b773be0bbca3", this) == 1) yield return null;
            var PublishEventNode34_Event = new GroupShouldSpawnEvent();
            System.Publish(PublishEventNode34_Event);
            PublishEventNode34_Result = PublishEventNode34_Event;
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode31_no() {
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode30_yes() {
            ActionNode31_component = this.Group;
            // ActionNode
            while (this.DebugInfo("0ba78f37-2228-48a9-aa07-f2076c7f5fdd","b77ce3ed-39d6-4f12-b4eb-b27fd3f871ab", this) == 1) yield return null;
            // Visit TetrisUtils.Update
            TetrisUtils.Update(ActionNode31_component, ()=> { System.StartCoroutine(ActionNode31_yes()); }, ()=> { System.StartCoroutine(ActionNode31_no()); });
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode30_no() {
            yield break;
        }
    }
}
