// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class GUISystemHandVisibleGreenEventHandler {
        
        public GreenLightComponent Group;
        
        private TetrisDB.HandVisibleEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode170_obj = default( UnityEngine.GameObject );
        
        private bool ActionNode170_state = default( System.Boolean );
        
        private bool BoolNode175 = true;
        
        public TetrisDB.HandVisibleEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode170_obj = Group.gameObject;
            ActionNode170_state = BoolNode175;
            // ActionNode
            while (this.DebugInfo("e3f5e492-b904-4a14-8c5a-b773be0bbca3","bf1a89a3-98e0-4803-b7a0-808be2646fd3", this) == 1) yield return null;
            // Visit GameObjectUtils.setActive
            GameObjectUtils.setActive(ActionNode170_obj, ActionNode170_state);
            yield break;
        }
    }
}
