// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class GUISystemMenuOpenEventHandler {
        
        public MenuComponent Group;
        
        private TetrisDB.MenuOpenEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode154_obj = default( UnityEngine.GameObject );
        
        private bool ActionNode154_state = default( System.Boolean );
        
        private bool BoolNode156 = true;
        
        public TetrisDB.MenuOpenEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode154_obj = Group.gameObject;
            ActionNode154_state = BoolNode156;
            // ActionNode
            while (this.DebugInfo("","d71fc2ae-16f0-41d1-af16-88375cbe2dab", this) == 1) yield return null;
            // Visit GameObjectUtils.setActive
            GameObjectUtils.setActive(ActionNode154_obj, ActionNode154_state);
            // SetVariableNode
            while (this.DebugInfo("d71fc2ae-16f0-41d1-af16-88375cbe2dab","13f67d59-c7bd-4904-a080-15ea16f8fcf6", this) == 1) yield return null;
            Group.isVisible = (System.Boolean)BoolNode156;
            yield break;
        }
    }
}
