// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class GUISystemHandVisibleRedEventHandler {
        
        public RedLightComponent Group;
        
        private TetrisDB.HandVisibleEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode176_obj = default( UnityEngine.GameObject );
        
        private bool ActionNode176_state = default( System.Boolean );
        
        private bool BoolNode177 = false;
        
        public TetrisDB.HandVisibleEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode176_obj = Group.gameObject;
            ActionNode176_state = BoolNode177;
            // ActionNode
            while (this.DebugInfo("8cb82bb7-2d9d-452b-ba92-12398c02e1b6","9cbc95df-ea2c-4181-9c07-104f64e2c26c", this) == 1) yield return null;
            // Visit GameObjectUtils.setActive
            GameObjectUtils.setActive(ActionNode176_obj, ActionNode176_state);
            yield break;
        }
    }
}
