// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class GUISystemMenuCloseEventHandler {
        
        public MenuComponent Group;
        
        private TetrisDB.MenuCloseEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode157_obj = default( UnityEngine.GameObject );
        
        private bool ActionNode157_state = default( System.Boolean );
        
        private bool BoolNode158 = false;
        
        public TetrisDB.MenuCloseEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode157_obj = Group.gameObject;
            ActionNode157_state = BoolNode158;
            // ActionNode
            while (this.DebugInfo("fa8d044e-dfc4-489d-a365-7c4b08bc0a19","214a8a05-5f19-40a6-8659-3bb971dc58c0", this) == 1) yield return null;
            // Visit GameObjectUtils.setActive
            GameObjectUtils.setActive(ActionNode157_obj, ActionNode157_state);
            // SetVariableNode
            while (this.DebugInfo("214a8a05-5f19-40a6-8659-3bb971dc58c0","afbc5001-5e11-44c9-bc89-603a26360905", this) == 1) yield return null;
            Group.isVisible = (System.Boolean)BoolNode158;
            yield break;
        }
    }
}
