// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class GUISystemGameExitEventHandler {
        
        public MenuComponent Group;
        
        private TetrisDB.GameExitEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private bool ActionNode162_value = default( System.Boolean );
        
        private object ActionNode166_message = default( System.Object );
        
        private string StringNode167 = "exit game";
        
        private object ActionNode168_message = default( System.Object );
        
        public TetrisDB.GameExitEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            ActionNode162_value = Group.isVisible;
            // ActionNode
            while (this.DebugInfo("cd61b2c4-389e-4936-bd8e-cd6af0ea41c0","236ef81c-ed44-4036-8bd4-a83a144844a0", this) == 1) yield return null;
            // Visit uFrame.Actions.Comparisons.IsTrue
            uFrame.Actions.Comparisons.IsTrue(ActionNode162_value, ()=> { System.StartCoroutine(ActionNode162_yes()); }, ()=> { System.StartCoroutine(ActionNode162_no()); });
            ActionNode168_message = Group.isVisible;
            // ActionNode
            while (this.DebugInfo("af030e73-3de9-46df-8d4a-9f69b6ec85ae","3f6df7b7-6f60-49de-b29f-9a23e23226d2", this) == 1) yield return null;
            // Visit uFrame.Actions.DebugLibrary.LogMessage
            uFrame.Actions.DebugLibrary.LogMessage(ActionNode168_message);
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode162_yes() {
            // ActionNode
            while (this.DebugInfo("236ef81c-ed44-4036-8bd4-a83a144844a0","9be5831a-7318-4df3-b7a9-e99ec75713ab", this) == 1) yield return null;
            // Visit GUIUtil.ExitGame
            GUIUtil.ExitGame();
            ActionNode166_message = StringNode167;
            // ActionNode
            while (this.DebugInfo("9be5831a-7318-4df3-b7a9-e99ec75713ab","af030e73-3de9-46df-8d4a-9f69b6ec85ae", this) == 1) yield return null;
            // Visit uFrame.Actions.DebugLibrary.LogMessage
            uFrame.Actions.DebugLibrary.LogMessage(ActionNode166_message);
            yield break;
        }
        
        private System.Collections.IEnumerator ActionNode162_no() {
            yield break;
        }
    }
}
