// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class SpawnEventGameReadyHandler {
        
        public SpawnComponent Group;
        
        private uFrame.Kernel.GameReadyEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private TetrisDB.GroupShouldSpawnEvent PublishEventNode1_Result = default( TetrisDB.GroupShouldSpawnEvent );
        
        public uFrame.Kernel.GameReadyEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // PublishEventNode
            while (this.DebugInfo("d3c2b90e-db35-4915-8fcb-8daaeb4e206e","63a4eb4a-bf6a-420c-b283-f294fcb6f703", this) == 1) yield return null;
            var PublishEventNode1_Event = new GroupShouldSpawnEvent();
            System.Publish(PublishEventNode1_Event);
            PublishEventNode1_Result = PublishEventNode1_Event;
            yield break;
        }
    }
}
