// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class SpawnEventGroupShouldSpawnEventHandler {
        
        public SpawnComponent Group;
        
        private TetrisDB.GroupShouldSpawnEvent _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private UnityEngine.GameObject ActionNode21_Result = default( UnityEngine.GameObject );
        
        private UnityEngine.GameObject ActionNode6_gameObject = default( UnityEngine.GameObject );
        
        private UnityEngine.Vector3 ActionNode6_position = default( UnityEngine.Vector3 );
        
        private UnityEngine.Vector3 ActionNode6_rotation = default( UnityEngine.Vector3 );
        
        private UnityEngine.GameObject ActionNode6_Result = default( UnityEngine.GameObject );
        
        public TetrisDB.GroupShouldSpawnEvent Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual System.Collections.IEnumerator Execute() {
            // ActionNode
            while (this.DebugInfo("3dbfd24a-fcdb-47eb-bd5c-08b10531dc5d","f7005e05-d0d9-4d94-b9aa-919b1ffd9b8e", this) == 1) yield return null;
            // Visit GameObjectUtil.getRandomGameObject
            ActionNode21_Result = GameObjectUtil.getRandomGameObject();
            ActionNode6_gameObject = ActionNode21_Result;
            ActionNode6_position = Group.transform.position;
            ActionNode6_rotation = Group.transform.rotation.eulerAngles;
            // ActionNode
            while (this.DebugInfo("f7005e05-d0d9-4d94-b9aa-919b1ffd9b8e","291ffeaa-dbda-403c-b412-a656b50143bf", this) == 1) yield return null;
            // Visit uFrame.Actions.GameObjects.Instantiate
            ActionNode6_Result = uFrame.Actions.GameObjects.Instantiate(ActionNode6_gameObject, ActionNode6_position, ActionNode6_rotation);
            yield break;
        }
    }
}
