// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(7)]
    [uFrame.Attributes.uFrameIdentifier("b6fffe07-6001-49d5-9bea-13633b286dac")]
    public partial class GreenLightComponent : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 7;
            }
        }
    }
}
