// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(3)]
    [uFrame.Attributes.uFrameIdentifier("d2972790-1685-4724-b4b9-00a00f7b4732")]
    public partial class GroupComponent : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Boolean _isActive;
        
        private Subject<PropertyChangedEvent<Boolean>> _isActiveObservable;
        
        private PropertyChangedEvent<Boolean> _isActiveEvent;
        
        public override int ComponentId {
            get {
                return 3;
            }
        }
        
        public IObservable<PropertyChangedEvent<Boolean>> isActiveObservable {
            get {
                return _isActiveObservable ?? (_isActiveObservable = new Subject<PropertyChangedEvent<Boolean>>());
            }
        }
        
        public Boolean isActive {
            get {
                return _isActive;
            }
            set {
                SetisActive(value);
            }
        }
        
        public virtual void SetisActive(Boolean value) {
            SetProperty(ref _isActive, value, ref _isActiveEvent, _isActiveObservable);
        }
    }
}
