// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using Invert.Json;
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(8)]
    [uFrame.Attributes.uFrameIdentifier("14e3ad5c-e957-4b69-80aa-fe49f859f4a1")]
    public partial class RedLightComponent : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 8;
            }
        }
    }
}
