// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    [UnityEditor.InitializeOnLoadAttribute()]
    [uFrame.Attributes.uFrameIdentifier("e11c28fe-ed9a-41d7-a2a4-61ef016fba9d")]
    public class TetrisDBEditorExtensions {
        
        [UnityEditor.MenuItem("GameObject/Create TetrisDB Kernel", false, 0)]
        public static void AddKernel() {
            Invert.uFrame.ECS.Templates.EcsEditorExtensionTemplate.AddEcsKernelWith<TetrisDB.TetrisDBLoader>();
        }
    }
}
