// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using TetrisDB;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UniRx;
    using UnityEngine;
    
    
    public partial class InputSystemBase : uFrame.ECS.EcsSystem, uFrame.ECS.ISystemUpdate {
        
        private IEcsComponentManagerOf<MenuComponent> _MenuComponentManager;
        
        private IEcsComponentManagerOf<GroupComponent> _GroupComponentManager;
        
        private IEcsComponentManagerOf<GreenLightComponent> _GreenLightComponentManager;
        
        private IEcsComponentManagerOf<RedLightComponent> _RedLightComponentManager;
        
        private IEcsComponentManagerOf<SpawnComponent> _SpawnComponentManager;
        
        public IEcsComponentManagerOf<MenuComponent> MenuComponentManager {
            get {
                return _MenuComponentManager;
            }
            set {
                _MenuComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<GroupComponent> GroupComponentManager {
            get {
                return _GroupComponentManager;
            }
            set {
                _GroupComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<GreenLightComponent> GreenLightComponentManager {
            get {
                return _GreenLightComponentManager;
            }
            set {
                _GreenLightComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<RedLightComponent> RedLightComponentManager {
            get {
                return _RedLightComponentManager;
            }
            set {
                _RedLightComponentManager = value;
            }
        }
        
        public IEcsComponentManagerOf<SpawnComponent> SpawnComponentManager {
            get {
                return _SpawnComponentManager;
            }
            set {
                _SpawnComponentManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            MenuComponentManager = ComponentSystem.RegisterComponent<MenuComponent>(4);
            GroupComponentManager = ComponentSystem.RegisterComponent<GroupComponent>(3);
            GreenLightComponentManager = ComponentSystem.RegisterComponent<GreenLightComponent>(7);
            RedLightComponentManager = ComponentSystem.RegisterComponent<RedLightComponent>(8);
            SpawnComponentManager = ComponentSystem.RegisterComponent<SpawnComponent>(1);
        }
        
        protected virtual void InputSystemUpdateHandler() {
            var handler = new InputSystemUpdateHandler();
            handler.System = this;
            StartCoroutine(handler.Execute());
        }
        
        protected void InputSystemUpdateFilter() {
            this.InputSystemUpdateHandler();
        }
        
        public virtual void SystemUpdate() {
            InputSystemUpdateFilter();
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("7a5010cc-faca-4a3e-ac2e-f0f5547f1ede")]
    public partial class InputSystem : InputSystemBase {
        
        private static InputSystem _Instance;
        
        public InputSystem() {
            Instance = this;
        }
        
        public static InputSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
