// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    [uFrame.Attributes.uFrameIdentifier("5bf54a8f-6f4d-41d2-8581-23ecf72b02b5")]
    public partial class SpawnEventLoader : uFrame.Kernel.SystemLoader {
        
        public override void Load() {
            this.AddSystem<SpawnEvent>();
        }
    }
}
