// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    #region 
static
    public class TetrisModuleExtensions {
        
        #region 
static
        public uFrame.ECS.IEcsComponentManagerOf<SpawnComponent> SpawnComponentManager(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<SpawnComponent>();
        }
        #endregion
        
        #region 
static
        public List<SpawnComponent> SpawnComponentComponents(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<SpawnComponent>().Components;
        }
        #endregion
    }
    #endregion
}
