// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TetrisDB {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    #region 
static
    public class TetrisModuleExtensions {
        
        #region 
static
        public uFrame.ECS.IEcsComponentManagerOf<MenuComponent> MenuComponentManager(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<MenuComponent>();
        }
        #endregion
        
        #region 
static
        public uFrame.ECS.IEcsComponentManagerOf<RedLightComponent> RedLightComponentManager(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<RedLightComponent>();
        }
        #endregion
        
        #region 
static
        public uFrame.ECS.IEcsComponentManagerOf<SpawnComponent> SpawnComponentManager(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<SpawnComponent>();
        }
        #endregion
        
        #region 
static
        public uFrame.ECS.IEcsComponentManagerOf<GreenLightComponent> GreenLightComponentManager(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<GreenLightComponent>();
        }
        #endregion
        
        #region 
static
        public uFrame.ECS.IEcsComponentManagerOf<GroupComponent> GroupComponentManager(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<GroupComponent>();
        }
        #endregion
        
        #region 
static
        public List<MenuComponent> MenuComponentComponents(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<MenuComponent>().Components;
        }
        #endregion
        
        #region 
static
        public List<RedLightComponent> RedLightComponentComponents(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<RedLightComponent>().Components;
        }
        #endregion
        
        #region 
static
        public List<SpawnComponent> SpawnComponentComponents(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<SpawnComponent>().Components;
        }
        #endregion
        
        #region 
static
        public List<GreenLightComponent> GreenLightComponentComponents(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<GreenLightComponent>().Components;
        }
        #endregion
        
        #region 
static
        public List<GroupComponent> GroupComponentComponents(this uFrame.ECS.IEcsSystem system) {
            return system.ComponentSystem.RegisterComponent<GroupComponent>().Components;
        }
        #endregion
    }
    #endregion
}
